# Lambda Python 3.12 베이스 이미지 사용
FROM public.ecr.aws/lambda/python:3.12

# 필요 시 requirements 설치
COPY requirements.txt .
RUN pip install -r requirements.txt

# main.py 복사
COPY ./app ${LAMBDA_TASK_ROOT}/app

ENV AWS_LAMBDA_FUNCTION_HANDLER=app.main.lambda_handler

# Lambda handler 설정 (파일명.함수명)
CMD ["app.main.lambda_handler"]